# -*- coding: utf-8 -*-
"""coba_1 copy 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQPsb_OtQdgfFFQbJ8mNsDFmZeJ-IjaK
"""

# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer


# Download stopwords from NLTK
nltk.download('stopwords')
nltk.download('wordnet')

"""# **Load data**"""

df = pd.read_csv('reliance_news_sentiment.csv')
df = df[['description', 'sentiment']]
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

cnt_pro = df['sentiment'].value_counts()
plt.figure(figsize=(12, 4))
sns.barplot(x=cnt_pro.index, y=cnt_pro.values, palette="viridis", alpha=0.8)
plt.ylabel('Number of Occurrences', fontsize=12)
plt.xlabel('Sentiment', fontsize=12)
plt.xticks(rotation=90)
plt.show()

"""# **Prepro**"""

from nltk.tokenize import word_tokenize

# Mendapatkan daftar stopwords
stop_words = set(stopwords.words('English'))
stemmer = PorterStemmer()

def preprocess_text(text):
    text = text.lower() 
    words = text.split() 
    text = ' '.join(words) 
    text = re.sub(r'[^a-zA-Z\s]', '', text) 
    tokens = word_tokenize(text)  
    tokens = [token for token in tokens if token not in stop_words]  
    tokens = [stemmer.stem(token) for token in tokens] 
    return ' '.join(tokens)  #

df['description'] = df['description'].apply(preprocess_text)


label_encoder = LabelEncoder()
df['sentiment'] = label_encoder.fit_transform(df['sentiment'])

"""# **Split Data**"""

import pandas as pd
from sklearn.model_selection import train_test_split

# Siapkan data untuk pelatihan
X = df['description'].values
y = df['sentiment'].values

# Bagi data menjadi data pelatihan dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# **Embeddings**"""

# Use TF-IDF for feature extraction
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train).toarray()
X_test_tfidf = tfidf_vectorizer.transform(X_test).toarray()

from imblearn.over_sampling import SMOTE

# Terapkan SMOTE pada data pelatihan
smote = SMOTE(random_state=42)
X_train_tfidf, y_train = smote.fit_resample(X_train_tfidf, y_train)

"""# Modelling"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Dropout, Bidirectional
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Definisikan model
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_tfidf.shape[1],), kernel_regularizer=regularizers.l2(0.001)),
    Dropout(0.3),
    Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    Dropout(0.3),
    Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    Dropout(0.2),
    Dense(3, activation='softmax')
])

# Compile model
optimizer = Adam(learning_rate=0.001)
model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=0.0001)

# Melatih model
history = model.fit(
    X_train_tfidf, y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_test_tfidf, y_test),
    callbacks=[early_stopping, reduce_lr],
    verbose=1
)

# Menyajikan ringkasan model
model.summary()

# Evaluate the model
loss, accuracy = model.evaluate(X_test_tfidf, y_test, verbose=0)
print(f'Test Accuracy: {accuracy:.4f}')

# Make predictions
y_pred = model.predict(X_test_tfidf)
y_pred_classes = np.argmax(y_pred, axis=1)

# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_classes))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_classes)

cm_df = pd.DataFrame(cm, index=label_encoder.classes_, columns=label_encoder.classes_)

plt.figure(figsize=(10, 7))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

import matplotlib.pyplot as plt

# Plot loss
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend()
plt.show()

# Plot accuracy
plt.plot(history.history['accuracy'], label='train accuracy')
plt.plot(history.history['val_accuracy'], label='val accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.title('Training and Validation Accuracy')
plt.legend()
plt.show()

model.save('sentiment_analysis_lstm_model.h5')

"""# Save Model"""

from tensorflow.keras.models import load_model

loaded_model = load_model('sentiment_analysis_lstm_model.h5')

"""# Nyoba"""

stop_words = set(stopwords.words('English'))
stemmer = PorterStemmer()

def preprocess_new_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    tokens = word_tokenize(text)
    tokens = [token for token in tokens if token not in stop_words]
    tokens = [stemmer.stem(token) for token in tokens]
    return ' '.join(tokens)

new_descriptions = ["I love this product!", "The service was terrible."]

# Melakukan preprocessing pada deskripsi baru
new_descriptions_processed = [preprocess_new_text(desc) for desc in new_descriptions]

# Mengubah teks baru menjadi representasi TF-IDF
new_tfidf = tfidf_vectorizer.transform(new_descriptions_processed).toarray()

# Melakukan prediksi
predictions = loaded_model.predict(new_tfidf)
predicted_classes = np.argmax(predictions, axis=1)

# Menampilkan hasil prediksi
for desc, pred in zip(new_descriptions, predicted_classes):
    sentiment = label_encoder.inverse_transform([pred])[0]
    print(f"Description: '{desc}' -> Predicted Sentiment: '{sentiment}'")
